### ISSUE TITLE
From Mappia

### ISSUE THREAD

**Issue by asfixia** [mfrang62/Mappia_Example#1]
Hi mfrang62,

something goes wrong with map publication?
Are you using the Mappia updated version?
We are working to improve, please report if any error occurs.

**Comment by SheriffM96** [comment]
Hi @asfixia. I am having a bit of an issue with my map. The interface is in another language. Any tips on how to change it to english? Thanks

https://maps.csr.ufmg.br/calculator/?queryid=152&storeurl=https://github.com/SheriffM96/Mappia_Example//&remotemap=GH:africa_countries;1,GH:nga_rds_1m_dcw;1,GH:nga_states;1

**Comment by asfixia** [comment]
Hi, glad you're using mappia.

You can use the following link: https://maps.csr.ufmg.br/calculator/?queryid=152&storeurl=https://github.com/SheriffM96/Mappia_Example//&remotemap=GH:africa_countries;1,GH:nga_rds_1m_dcw;1,GH:nga_states;1&lang=eng

TIP: For a better result you can increase the zoom max level for your "nga_rds_1m_dcw" layer.

**Comment by SheriffM96** [comment]
Hi Asfixia,

Thank you soo much for your help. However, this is just a test map that i used to see how the plugin works. Can you please tell me how to change the language incase I encounter thesame problem again with another map or account? Thanks
